apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpd-base
spec:
  ingressClassName: nginx
  rules:
  - host: httpd-base.azdevopsb82.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpd-base
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-base
spec:
  ingressClassName: nginx
  rules:
  - host: nginx-base.azdevopsb82.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-base
            port:
              number: 80




