apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-demo
data:
  URL: google.com
  domain: www.google.com
  company: google
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-demo-1
spec:
  containers:
  - name: debug
    image: rkalluru/debug
    env:
      - name: URL
        valueFrom:
          configMapKeyRef:
            name: cm-demo           # The ConfigMap this value comes from.
            key: URL # The key to fetch.
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-demo-2
spec:
  containers:
  - name: debug
    image: rkalluru/debug
    envFrom:
      - configMapRef:
          name: cm-demo

---
apiVersion: v1
kind: Pod
metadata:
  name: cm-demo-3
spec:
  containers:
  - name: debug
    image: rkalluru/debug
    volumeMounts:
    - name: cm
      mountPath: "/data"
      readOnly: true
  volumes:
  - name: cm
    configMap:
      name: cm-demo




