apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  message: SGVsbG8gV29ybGQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-1
spec:
  containers:
  - name: debug
    image: rkalluru/debug
    env:
      - name: URL
        valueFrom:
          secretKeyRef:
            name: secret-demo
            key: message
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-2
spec:
  containers:
  - name: debug
    image: rkalluru/debug
    envFrom:
    - secretRef:
        name: secret-demo

