apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  storageClassName: "managed"
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  volumes:
    - name: demo-pvc
      persistentVolumeClaim:
        claimName: demo-pvc
  containers:
    - name: debug
      image: rkalluru/debug
      volumeMounts:
        - mountPath: "/data"
          name: demo-pvc






