---
apiVersion: v1
kind: Namespace
metadata:
  name: example
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-method
  namespace: example
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug
  namespace: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-method
  namespace: example
  labels:
    app: http-method
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-method
  template:
    metadata:
      labels:
        app: http-method
    spec:
      serviceAccountName: http-method
      containers:
      - name: http-method
        image: rkalluru/http-methods
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: http-method
  namespace: example
spec:
  selector:
    app: http-method
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  namespace: example
  labels:
    app: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      serviceAccountName: debug
      containers:
      - name: debug
        image: rkalluru/debug

---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: example
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: get-allow
  namespace: example
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/default/sa/sleep"]
    - source:
        namespaces: ["test"]
    to:
    - operation:
        methods: ["GET"]
        paths: ["/info*"]
    - operation:
        methods: ["POST"]
        paths: ["/data"]
    when:
    - key: request.auth.claims[iss]
      values: ["https://accounts.google.com"]


