---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
data:
  "APP_GIT_URL": "https://github.com/roboshop-devops-project-v3/shipping"
  "CART_ENDPOINT": "cart-dev.azdevopsb82.online:8080"
  "DB_HOST": "mysql-dev.azdevopsb82.online"
  "DB_PASS": "RoboShop@1"
  "DB_TYPE": "mysql"
  "DB_USER": "root"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema-app-user
spec:
  template:
    spec:
      containers:
      - name: shipping-schema-app-user
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env:
          - name: SCHEMA_FILE
            value: "db/app-user.sql"
        envFrom:
          - configMapRef:
              name: shipping
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema-schema
spec:
  template:
    spec:
      containers:
      - name: shipping-schema-schema
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env:
          - name: SCHEMA_FILE
            value: "db/schema.sql"
        envFrom:
          - configMapRef:
              name: shipping
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shipping-schema-master-data
spec:
  template:
    spec:
      containers:
      - name: shipping-schema-master-data
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
        env:
          - name: SCHEMA_FILE
            value: "db/master-data.sql"
        envFrom:
          - configMapRef:
              name: shipping
      restartPolicy: Never
  backoffLimit: 1


